### ISSUE TITLE
Simple feature : Display abilities learned in game

### ISSUE THREAD

**Issue by calamina** [olistic/warriorjs#116]
At the moment we discover new abilities in the readme only (which is pretty logic since we can implement them right away).

Though I feel it could be a nice addition to the endlevel score like :

`Abilities learned : *****`
or
`warriorname  learned *****`

It would feel like an additional "reward" for completing the level !

**Comment by A1rPun** [comment]
After you beat a floor you get asked if you want to retry it. If you get the additional reward message and you want to retry the current floor does that mean that you can use the new abilities for the current floor? The message can be confusing at this point. 

The new learned abilities are properties of a floor so that means the current floor needs to get data from the next floor to display the abilities which sounds counterintuitive (I'm not saying this is impossible).

I agree we could have some extra reward after you beat a floor, like ascii fireworks or something :).

**Comment by olistic** [comment]
I would happily accept a PR that marks as `**NEW**` abilities that have just been learned in the README of the unlocked level. Feel free to reopen this issue if you want to grab this.
