### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by ecwyne** [olistic/warriorjs#22]
Have you seen or considered using https://github.com/qiao/PathFinding.js?

**Comment by olistic** [comment]
No, I've never seen it before but the project looks really really great! About using it in WarriorJS, I don't consider it appropriate. And the reason is that one of the difficulties of some levels (specially the ones that will come with the advanced tower) is that the players need to program their own path-finding algorithms using the different senses the warrior has available. And most of the time in WarriorJS, the optimal path doesn't match the shortest, because the player must decide many other things apart from the direction in which to walk. Will he or she aim to kill all the enemies, or will he avoid them if possible? Will he or she rescue the prisoners or will try to get to the stairs as faster as possible?

Anyway, thanks for the suggestion.
