### ISSUE TITLE
warriorjs command not creating directory

### ISSUE THREAD

**Issue by newswim** [olistic/warriorjs#29]
I ran `npm install -g warriorjs` and then `warriorjs` and then nothing.

complained it couldn't find 'yargs', installed that, then i didn't have 'glob', installed that. Now it all works fine.. I think this is a dependency issue? I'm still kind of green to how npm does dependency management. Cheers!

**Comment by olistic** [comment]
It is fixed in 1.2.2, just run `npm update -g warriorjs`.

This was indeed a problem with the dependencies. I hadn't noticed before cause npm v3 installs the dependencies in the project `node_modules` without nesting, and 'yargs' and 'glob' were already being installed by other dependencies. However, if you are running a version of npm < 3 (which is probably your case), then it complains.

Thanks!
