### ISSUE TITLE
function to get the type of the enemy

### ISSUE THREAD

**Issue by david-gang** [olistic/warriorjs#37]
Hi,

I would like to get the information of the type of the enemy and not just if an enemy is at the certain unit.
This will make it easier to design a strategy.
Also in level 7 it was a bit odd because i was in the middle of two enemies and did not "know" (mean without looking at the README) if the archer was on the right or left side. This is a bit odd.

Thanks,
David

**Comment by olistic** [comment]
Hello @david-gang, I'm closing old issues to create a fresh backlog for the project. I'll evaluate your issue and consider adding it to the backlog. Thanks!

**Comment by JayAndCatchFire** [comment]
FWIW, I think this should be left up to the player to do.

For example, as of level 5 I have the following code to detect the type of thing using an enumerable instead of just relying on the Space API.

```js
function Enum (...args) {
  if (!(this instanceof Enum)) {
    return new Enum(...args);
  }

  for (let arg of args) {
    this[arg] = Symbol(arg);
  }
}

const THING = new Enum(
  'CAPTIVE',
  'ENEMY',
  'NOTHING',
);

function getType(thing) {
  switch (true) {
    case thing.isCaptive():
      return THING.CAPTIVE;

    case thing.isEmpty():
      return THING.NOTHING;

    case thing.isEnemy():
      return THING.ENEMY;

    default:
      throw new Error('Unknown "thing" found!');
  }
}
```

Part of the joy of this game for me is working _around_ the Warrior API and Space API.  It's not that they're bad APIs.  They're just minimalistic.
