### ISSUE TITLE
IDE?

### ISSUE THREAD

**Issue by rorymurphyza** [olistic/warriorjs#38]
Hi guys. Not so much an issue as a question.
What IDE do you recommend I work from to get started on this project? I am completely new to JS and I thought that playing this game would be a great way to get started.
I am currently using Visual Studio but it is not great with JS. IntelliSense doesn't work nicely and I can't compile to check for syntax errors. I have managed to make it to Beginner Level 7 so far with this, but I was thinking that there must be an easier way to do this?

Thanks so much for the game, I am really enjoying it so far and I think I am starting to get the hang of JS.

**Comment by tvl83** [comment]
Check out webstorm. It's an awesome ide for web development. 30 trail
available. They changed they pricing structure so I don't know how much it
costs but it's worth the license fee. They update it regularly. I've used
webstorm and the other ides from that company, jetbrains, for a couple
years now and love them.

**Comment by mattwilsn** [comment]
I have used webstorm, sublime. I like them all for different reasons. Webstorm is more of a convention based as most of anything you will every need is built in. Where sublime is more configuration, plugins overload. I would say if you are doing front end ( html, js, css ) sublime is a good choice because  of how simple and light it is. If you are doing server side (node js ) or more complex work  then use webstorm so you can run, debug and test in one window.

**Comment by nachoaIvarez** [comment]
@rorymurphyza I use Atom, but if you're starting out with JS, WebStorm will help you a lot! Give it a try!

**Comment by rorymurphyza** [comment]
Thanks for the suggestions. I'm downloading WebStorm at the moment and looking forwards to getting going on it.

**Comment by everystone** [comment]
[Visual Studio Code](https://code.visualstudio.com) is free and works great with ES2015 etc.
