### ISSUE TITLE
🐛 `console.log` not working in player.js

### ISSUE THREAD

**Issue by jakehamilton** [olistic/warriorjs#69]
# Environment

```
  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 8.48 GB / 15.86 GB
  Binaries:
    Yarn: 1.5.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 5.7.1 - C:\Program Files\nodejs\npm.CMD
  Virtualization:
    Docker: 18.03.0 - C:\Program Files\Docker\Docker\Resources\bin\docker.EXE
  IDEs:
    VSCode: 1.23.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.12 - C:\Program Files\Git\usr\bin\bash.EXE
    Python: 2.7.14 - /c/Python27/python
  Browsers:
    Edge: 42.17666.1000.0
    Internet Explorer: 11.0.17666.1000
```

# Steps to reproduce

1. Install warriorjs

  + `npm i -g warriorjs`

2. Bootstrap with warriorjs

  + `warriorjs` (follow default config)

3. Open `Player.js` and add a `console.log('hello')` statement in the `playTurn` method

  + `playTurn () { console.log('Hello World'); }`

4. Run warriorjs

  + `warriorjs` (select your character to run)

5. The log is not displayed

# Expected Behavior

All `console` statements should be displayed in the output (or at least logged to a file).

# Actual Behavior

No `console` statements display.

# Additional Notes

So far I think the issue comes from running in a new vm context. That call happens here: https://github.com/olistic/warriorjs/blob/master/packages/warriorjs-core/src/PlayerLoader.js#L23

And finally, this is a really cool project. Thanks to everyone for the great work so far!

**Comment by olistic** [comment]
Hey @jakehamilton! Thanks for your detailed issue, I agree that something like this is needed (as other people have asked in the past: #41).

I'm going to take the time to think how this could be best implemented. I could inject `console` inside the VM context, but because of the way the play log is printed, the `console.log` calls would be hoisted instead of being inline with the play events. The other options I'm exploring so far are:

* Monkey-patching `console.log` with [`Logger`](https://github.com/olistic/warriorjs/blob/30d96d0f98c7b9e450010dac830c0ca11541d37d/packages/warriorjs-core/src/Logger.js). This has the advantage to preserve the existing logging interface already known by JS devs, but maybe feels a bit awkward implementation-wise.
* Adding `warrior.say()` ability that logs the message to the console in the form of `> Spartacus says "blah blah blah"`. This feels more in sync with the APIs in the game and requires less magic to implement, but it breaks a bit the separation between the core and the abilities that already exists.

Any suggestion is welcome, and thanks again.

**Comment by jakehamilton** [comment]
@olistic thanks for the quick reply! So far I'm thinking something along the lines of `warrior.say()` would feel the best to use. Though, there is the issue of a name collision in the future should a warrior ever be able to `say` anything in the context of a level. Perhaps a separate logs section for each turn is a better solution?

`warrior.say` would need to have some thought put in to logging complex values (if that is desired):

```
-------------------------------------------- turn 001 --------------------------------------------
♥ 20
╔════════╗
║C  @S aa║
╚════════╝
> Spartacus says "{ some: { json: 'object' } }"
```

A separate logs section doesn't look too bad:

```
-------------------------------------------- turn 001 --------------------------------------------
♥ 20
╔════════╗
║C  @S aa║
╚════════╝
> Spartacus walks forward

╔══════════════════════════════════════════════LOGS══════════════════════════════════════════════╗
║ 1.                                                                                             ║
║   {                                                                                            ║
║     some: {                                                                                    ║
║       json: 'object'                                                                           ║
║     }                                                                                          ║
║   }                                                                                            ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
```

Perhaps a little theming within the context of the world would help it fit in better:

```
-------------------------------------------- turn 001 --------------------------------------------
♥ 20
╔════════╗
║C  @S aa║
╚════════╝
> Spartacus walks forward
> Spartacus added entry #1 to the journal

╔═════════════════════════════════════════════JOURNAL════════════════════════════════════════════╗
║ 1.                                                                                             ║
║   {                                                                                            ║
║     some: {                                                                                    ║
║       json: 'object'                                                                           ║
║     }                                                                                          ║
║   }                                                                                            ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by benfletcher** [comment]
`warrior.journal()` could log to a `journal.txt` file or just output to terminal.

Just a thought to keep the logging "in character" with the game, as if the warrior was carrying a journal and taking notes in it to aid progress.

**Comment by olistic** [comment]
Another option in those same lines (but that doesn't interfere with the `warrior`'s namespace) could be to pass a `journal` parameter to the `playTurn` function that allows the player to log to said journal.

Example:
```js
class Player {
  playTurn(warrior, journal) {
    if (warrior.feel().isEmpty()) {
      journal.write("I'm not sure if I should work here...");
      warrior.walk();
    }
  }
}
```

I'm not sure if I like it yet, though.

**Comment by GavinRay97** [comment]
@olistic 

I went ahead and made an example implementation of this because I wanted to see if I could check the enemy type ahead of me with `feel()` (is this cheating? :eyes:)

I exposed two functions to the Player instance, `this.say()`, and `this.debug()`

```js
// PlayerLoader.createPlayer()
// See other implementations in 'Logger.js', 'ui/printDebugMessage.js', and 'ui/printPlay.js'
player.say = (...messages) => Logger.log(messages.length > 1 ? messages : messages[0]);
player.debug = (...args) => console.log(util.inspect(args, {showHidden: false, depth: null, colors: true}));
```

These are the results of calling
```js
this.debug(warrior.feel())
this.say(warrior.feel().toJSON())
```

`say()` uses the Logger instance to pass what is supposed to be a short/concise log statement into the player's turn:

![](https://i.imgur.com/lu1dFYF.png)

`debug()` allows you do a more thorough inspection, outside of the CLI's "in-game" UI:

![](https://i.imgur.com/AeM6JbQ.png)

**The code probably isn't very good, it's a LARGE project and I did the best I could with what I could make out and infer from the stuff you'd already written.**

**If you want to take a look, it's here:**
https://github.com/GavinRay97/warriorjs/tree/feature/logger

**Code Diff:**
https://github.com/olistic/warriorjs/compare/master...GavinRay97:feature/logger

**Comment by GavinRay97** [comment]
Just noticed there's a bug with the console styling switching between bold and not. I'll fix that later :joy:

**Comment by pajtai** [comment]
I found using the debugger super helpful.

It's easiest with a local npm install:

```
npm i @warriorjs/cli
```

and then add an index.js as follows

```javascript
'use strict';

require('@warriorjs/cli/bin/warriorjs');
```

now you can debug with:

`node --inspect index.js` - just drop a debugger in player.js and play around with the commands.

**Comment by GavinRay97** [comment]
@pajtai Ahhh, I didn't think of that. I thought about running with the `--inspect` command but then realized `warriorjs` was a bin and not ran via Node. That's much more clever, though! :+1:

**Comment by olistic** [comment]
@jakehamilton @benfletcher @GavinRay97 @pajtai I decided to implement a basic solution for this issue in #102. Please check it out (and maybe try it), any feedback is appreciated.

**Comment by olistic** [comment]
WarriorJS v0.3.0 includes a `think` ability that can be used as an alternative for `console.log`. It's not perfect yet, but I think it's good enough for now. Let me know if you have any feedback, I'm closing this ticket now.

**Comment by cavejay** [comment]
warriorjs v3.0.0 is live on npm but doesn't seem to enable this `think` ability in my profile. Is it hidden because it's not perfect yet or do I have to do something to my profile to refresh and have access to the new ability?

**Comment by olistic** [comment]
@cavejay you’re probably installing the old package, `warriorjs`, instead of `@warriorjs/cli`.

**Comment by cavejay** [comment]
yup. that was it. Was trying to figure out why my readme's weren't markdown as well. This would explain it
