### ISSUE TITLE
More beautiful welcome message

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#74]
Right now, the "Welcome to WarriorJS" message has a lot of room for improvement:

![screen shot 2018-05-11 at 18 06 13](https://user-images.githubusercontent.com/5600126/39946831-1e4e313c-5546-11e8-8465-418fbc021d22.png)

**Ideas and suggestions are welcome!**

**Comment by RascalTwo** [comment]
The only idea I can think of is having the logo in the terminal:

![current logo](https://github.com/olistic/warriorjs/raw/master/logo/warriorjs-banner-dark.png?raw=true)

![warriorjs-ascii](https://user-images.githubusercontent.com/9403665/39971534-d18de2f8-56ca-11e8-911d-d1073ba5e185.png)

It's got some work to be done before being perfect - mainly on the sword - but it looks better then nothing.

Since we already have `getScreenSize()`, we can safely output it only when the screen is wide enough.

*****

Here's the actual text for others to improve upon if they wish:

```
                                    ▁▁▁
                                    ▏●▕
                                    ▔▔▔
                                    ▌ ▐
                                    ▌ ▐
                                   ▂▄█▄▂
                                 ▞▀▀▀ ▀▀▀▚
                                    ● ●
▝█▖        ▗█▘▗▖    █▀▀▀▜▖ █▀▀▀▜▖   ● ●   ▗████▖ █▀▀▀▜▖     █ ▗████▛
 ▝█▖  ▗▖  ▗█▘▗██▖   █    █ █    █   ● ●   █▘  ▝█ █    █     █ █ 
  ▝█▖▗██▖▗█▘▗█▘▝█▖  █▄▄▄▟▘ █▄▄▄▟▘   ● ●   █    █ █▄▄▄▟▘     █ ▝████▖
   ▝██▘▝██▘▗█▄▄▄▄█▖ █  ▝█▖ █  ▝█▖   ● ●   █▖  ▗█ █  ▝█▖ █   █      █
    ▐▌  ▐▌▗█▘    ▝█▖█   ▝█▖█   ▝█▖  ● ●   ▝████▘ █   ▝█▖▝▙▄▟▘ ▟████▘
                                    ● ●
                                    ● ●
                                    ● ●
                                    ● ●
                                    ▚ ▞ 
                                     ▀
```

> It doesn't look correct in most text editors, you gotta view it in a terminal for the spacing to line up perfectly.

It's made with mostly [unicode bock elements](https://en.wikipedia.org/wiki/Block_Elements), thought it would look fuller then a bunch of `@` symbols.

**Comment by RascalTwo** [comment]
I made the sword more sword-like when implementing your changes, and it looks nice with the colored sword:

![warriorjs logo](https://user-images.githubusercontent.com/9403665/40094490-5d21a7ac-5895-11e8-928c-9b20c2ca1d34.png)

**Comment by Eveneit** [comment]
I'm not versed in ASCII art, so instead of a full-fledged logo I've designed this little thing (in ~1min so I'm sure someone can do way better with some work !)  :
![warrior2](https://user-images.githubusercontent.com/5458121/40168981-34d73f60-59c5-11e8-86e7-69c8aa3ee940.png)
Imo this kind of little logo it is closer to the "design" of the game than RascalTwo's proposition.

Else I've got two nice results using this site ([TAAG](http://patorjk.com/software/taag/#p=display&f=3D%20Diagonal&t=warriorJS)), that could be good for inspiration but I still think a custom message would be better :
![warrior](https://user-images.githubusercontent.com/5458121/40167971-b714309e-59c2-11e8-8b90-e13ad18b3d92.png)

**Comment by Eveneit** [comment]
Small update to show how it looks ingame :

![warriorlogo](https://user-images.githubusercontent.com/5458121/40205163-55209828-5a2b-11e8-91a1-3a6696fe5ce0.png)
