### ISSUE TITLE
How to start intermediate mode game

### ISSUE THREAD

**Issue by joshstrange** [olistic/warriorjs#75]
How do you start intermediate mode? I finished easy mode and I see references in the code and in issues about the intermediate mode but I can't figure out how to play it.

**Comment by olistic** [comment]
Hello @joshstrange, the reason it's not available yet is because it's being play-tested. If you want to play it and give feedback, that'd be awesome. You can find instructions [here](https://spectrum.chat/warriorjs/help?thread=65415831-132a-4c15-8c75-848d941daffe).

Closing as there's no more action to take. Feel free to continue the discussion in the linked thread.
