### ISSUE TITLE
Invalid submitted code. You must define a Player class!

### ISSUE THREAD

**Issue by kdorland** [olistic/warriorjs#89]
Game seems to be bugged in my environment (Windows 10, newest nodejs just installed). I'm getting the following:

![image](https://user-images.githubusercontent.com/579527/39969441-f942a8c2-56db-11e8-9c56-ce79064307cd.png)

# Environment
C:\Users\krist>npx envinfo --system --binaries --npmPackages *warriorjs* --npmGlobalPackages *warriorjs* --markdown
npx: installed 1 in 2.464s
The "path" argument must be of type string. Received type undefined
npx: installed 1 in 2.549s
C:\Users\krist\AppData\Roaming\npm-cache\_npx\13496\node_modules\envinfo\dist\cli.js
(node:13496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'devDependencies' of null
    at Promise.all.i.getPackageJsonByPath.then.e (C:\Users\krist\AppData\Roaming\npm-cache\_npx\13496\node_modules\envinfo\dist\cli.js:2:72540)
(node:13496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by olistic** [comment]
Hello @kdorland, thanks for your interest in the project! Node 10 is failing to copy the template code due to a problem with one of the warriorjs' dependencies that wasn't compatible with that version. I have already updated that in #81, I'm going to publish a new release soon. Meanwhile, you should be able to play using Node 8 (the LTS version).

I'm going to close this now as there's no more action needed here. Feel free to re-open if after trying Node 8 (or the new release of warriorjs with Node 10) you still experience this problem.
